### PR TITLE
Add typescript declaration file

### PR DESCRIPTION
**Pull request by dprokop**
Hey @christo-pr, thanks for writing this library!

We want to use it at [Grafana](https://grafana.com). I've created a d.ts file that we use internally(https://github.com/grafana/grafana/pull/26413), I thought you mind find it useful to provide Typescript definition for consumers of your lib :)

### CODE REVIEW

**Comment by christo-pr** [comment]
Hey @dprokop, I'm glad it help you!
Sure, i'll merge it and bump the version to include the declaration file on the next minor release! Thanks for contributing

**Review by christo-pr — APPROVED** [review]
LGTM

**Comment by christo-pr** [comment]
Done @dprokop ,  version [1.0.7](https://github.com/christo-pr/dangerously-set-html-content/releases/tag/v1.0.7) include the typescript definition file. Thanks!

**Comment by dprokop** [comment]
@christo-pr perfect, thank you!

**Comment by KuulArt** [comment]
TS definition file does not exist when installing package through npm - I had to manually add definition. Version 1.0.7.
image

**Comment by christo-pr** [comment]
Hey @KuulArt! Thanks for notice the issue! Should be fixed now in `v1.0.8`

**Pull request merged**
